---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: frontend
          image: nova-frontend
          envFrom:
            - configMapRef:
                name: config-file
            - configMapRef:
                name: frontend-config-file
          # resources:
          #   requests:
          #     cpu: 25m
          #     memory: 300M
          #   limits:
          #     cpu: 50m
          #     memory: 400M
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000
      name: frontend
    - port: 80
      targetPort: 3000
      name: frontend-http
