apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: core
build:
  artifacts:
    - image: nova-backend
      context: backend
      docker:
        dockerfile: Dockerfile.dev
    - image: nova-frontend
      context: frontend
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
    - image: nova-admin
      context: admin
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1

deploy:
  kustomize:
    paths:
      - k8s/environment/overlays/local
