apiVersion: batch/v1
kind: Job
metadata:
  generateName: app-backend-healthcheck-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: backend-healthcheck
          image: curlimages/curl
          command:
            - "curl"
            - "-v"
            - "backend.staging.novalearn.org/health"
      restartPolicy: Never
  backoffLimit: 2
